- source/_posts/2017/2017-02-20-statie-how-to-run-it-locally.md
Error:
```
[Symfony\Component\Console\Exception\RuntimeException]
Not enough arguments (missing: "source").
```
> Fix generate argument

- source/_posts/2015/2015-11-02-ovladni-doctrine-migrace-v-nette.md
- source/_posts/2015/2015-11-09-4-zhave-novinky-v-symfony-3.md
- source/_posts/2015/2015-11-16-jak-si-udelat-web-i-bez-ajtaka.md
- source/_posts/2015/2015-12-20-to-nejlepsi-ze-symfonyconu-2015.md
- source/_posts/2016/2016-12-09-jak-se-vyporadat-s-hejty-v-komentarich.md
- source/_posts/2017/2017-01-10-jak-psat-zajimave-inzeraty-pro-ajtaky.md
- source/_posts/2017/2017-01-15-7-rad-ktere-bych-si-dal-pred-odchodem-na-vysokou-skolu.md
- source/_snippets/post/singlePostPreview.latte
- source/czech-posts.latte
- source/deprecated-posts.latte
- source/index.latte
Many people still comment posts that are deprecated or in Czech. But those are hidden in main page list and it's impossible to find them again.
**This fixes that**
---
> Add Deprecated and Czech posts section

- source/_posts/2018/2018-02-19-rector-part-1-what-and-how.md
Argument and attribute name should be named `$logger`, not `$loggerInterface` since it's concrete implementation. And there was fatal error - calling `log()` on `null` ;-)
> Fixed refactoring example for Rector

- source/_layouts/post.twig
- source/_snippets/post/postMetadataLine.twig
Most people find typos *after* reading the post, so having CTA only in the top makes no sense. I keep it there for quick edits and back compatbility, but also add under the post.
Closes #442
> move fix CTA under the post, where are some errors

- source/_posts/2018/2018-09-17-7-tips-to-write-exceptions-everyone-will-love.md
Remove unnecessary quotation mark from "7 Tips to Write Exceptions Everyone Will Love" article.
> Remove unnecessary quotation mark

- source/_posts/2018/2018-09-17-7-tips-to-write-exceptions-everyone-will-love.md
Fix a typo in "7 Tips to Write Exceptions Everyone Will Love" article. You wrote "Filer" instead of "Filter".
> Fix a typo in article

- source/_posts/2018/2018-11-15-how-to-get-php-74-typed-properties-to-your-code-in-few-seconds.md
I think there should be `declare(strict_types=1);` in all code examples which are using typed properties since you need to declare the strict type to enforce type checking. Same as parameter type hints.
> Added strict_types=1 to code examples

- source/_posts/2018/2018-08-16-whats-new-in-php-73-in-30-seconds-in-diffs.md
Because `json_decode('{}', null, null);` gives
> PHP Warning:  json_decode(): Depth must be greater than zero
> Fix `json_decode()` arguments

- .travis.yml
- composer.json
- ecs.yaml
- source/_data/generated/php_framework_trends.yaml
- source/_layouts/post.twig
- source/_snippets/footer.twig
- source/assets/css/style.css
- source/contact.twig
- source/php-framework-trends.twig
- src/ArrayUtils.php
- src/Command/GeneratePackageStatsCommand.php
- src/Exception/ShouldNotHappenException.php
- src/Json/FileToJsonLoader.php
- src/Packagist/PackageMonthlyDownloadsProvider.php
- src/Packagist/VendorPackagesProvider.php
- src/Statistics.php
- statie.yaml
> Add PHP Framework Trends page with composer statistics

- source/rss.twig
- statie.yaml
Redirect `/blog/` -> `/` might be useful too
> Fix invalid RSS website link

- source/_posts/2019/2019-11-18-how-to-delegate-code-reviews-to-ci.md
Starting to count at 0 might be subject to change – but I consider it better to keep GitHub instructions next to each other.
Additionally, the link to the GitHub Actions CI Feedback might have to be adjusted after merging https://github.com/TomasVotruba/rector-ci-demo/pull/1
> Include GitHub Actions instructions

- source/_posts/2019/2019-11-04-still-on-phpunit-4-come-to-phpunit-8-together-in-a-day.md
Since createMock might not be available, but mockBuilder has for a while (and allows for customizing the mocked result with disabling ctors / only specifying certain methods et al)
> Promote the use of mockBuilder()

- source/_posts/2018/2018-06-14-collector-pattern-for-dummies.md
The first version of the `calculate()` method had undefined variable. Then the formula was changing even though the change was not needed to make the point. But when I was reading the article I got fixated on the VAT formula change :)
> Standardize the VAT formula through the method evolution

- packages/blog/src/Repository/PostRepository.php
- packages/blog/templates/blog/archive.twig
- src/Controller/BlogArchiveController.php
- src/Controller/CleaningLadyListController.php
- templates/_snippets/footer.twig
- templates/_snippets/sponsor_button.twig
- templates/blog/post.twig
- templates/cleaning_lady_list.twig
- templates/index.twig
- templates/talks.twig
- merge archive to single one, misc
- remove sponsor on every header
According to Google Analytics, people visit all archives quite often. When they look for a creating post from *that* year... it must be frustrating to click into 3 pages and use CTRL + F. This will make it easier with just one page.
---
<br>
<br>
<br>
> unite archive

- templates/rss.twig
At this moment RSS returns description as markdown which isn't readable by RSS readers, with this small change it fix problem.
Hope You gonna accept and keep writing! 
(Feedly reader for example)
> Fix raw text for description

- packages/blog/data/2018/2018-05-10-rectify-turn-all-action-injects-to-constructor-injection-in-your-symfony-application.md
Here https://getrector.org/blog/2021/02/01/how-to-change-symfony-action-injects-to-constructor-injection
> [post] deprecat action inject, move to rector

- packages/blog/data/2019/2019-02-28-how-to-upgrade-symfony-2-8-to-3-4.md
For Symfony 3.0 to Symfony 3.4 the class is `SetList` instead of `SymfonySetList`
> Fix SetList usage instead of SymfonySetList

- resources/posts/2018/2018-06-07-how-to-migrate-from-php-cs-fixer-to-easy-coding-standard.md
Fixed code block syntax causing the blog style to not be presented correctly.
https://tomasvotruba.com/blog/2018/06/07/how-to-migrate-from-php-cs-fixer-to-easy-coding-standard#:~:text=cs%2Dfixer%20fix-,to%20ECS%20equivalent%3A,-vendor/bin/ecs
> Fixed code block syntax

- app/Repository/PostRepository.php
slug seems never be a key, it is the values of the `$this->posts` data, so mark slug as key always never exists, see
https://github.com/TomasVotruba/tomasvotruba.com/blob/08a6986ad9211d703ffff1a9d4aead189a4e0d6f/app/Repository/PostRepository.php#L79
use loop and compare its value instead per previous check.
> Remove unnecessary check $this->posts[$slug] on PostRepository

- app/Repository/PostRepository.php
On prod environment with debug 0, it should provide 404 page instead of 500 when it pointed to invalid slug:
**Before**
**After**
> Use NotFoundHttpException to produce 404 page on slug not found

- resources/posts/2019/2019-03-21-how-to-instantly-migrate-phpspec-to-phpunit.md
Hi, 
I was checking on how to migrate phpspec to phpunit when I found your blog article about it https://tomasvotruba.com/blog/2019/03/21/how-to-instantly-migrate-phpspec-to-phpunit
I tried it and figured I missed some information to make it work properly. 
Here is a PR to fix the article acording to that. 
By the way, thank you for your amazing work for the whole php community.
> docs: update phpspec migration blog post
