source/_posts/2016-06-17-filters-pattern-in-nette-database.md
Also drop unnecessary code style
=> add protip for column check

.gitignore, app/SculpinKernel.php, app/config/sculpin_site.yml, bin/deploy-gh-pages.sh, composer.json, packages/tomasvotruba/sculpin-blog-bundle/composer.json, packages/tomasvotruba/sculpin-blog-bundle/src/Resources/templates/partials/postMetadataLine.twig, packages/tomasvotruba/sculpin-blog-bundle/src/Resources/templates/partials/postPreview.twig, packages/tomasvotruba/sculpin-blog-bundle/src/Twig/SculpinBlogExtension.php, packages/tomasvotruba/sculpin-translation-bundle/composer.json, packages/tomasvotruba/sculpin-translation-bundle/src/Resources/config/services.yml, source/_posts/2016-09-19-how-to-get-more-than-request-in-controller-action.md, source/blog.twig, translations/post.cs.yml
- use https://github.com/Symplify/PHP7_Sculpin instead
=> PR link + action autowire article + switch to PHP7_Sculpin 

gulpfile.js, source/_posts/2017/2017-02-15-minimalistic-way-to-create-your-first-nette-extension.md, source/_posts/2017/2017-02-22-fast-and-easy-way-to-learn-complex-topics.md
Ping @enumag 
What do you think?
=> Decouple learning tips from Nette Extension post

source/_posts/2017/2017-02-20-statie-how-to-run-it-locally.md
=> Added: windows use

source/_posts/2016/2016-03-10-autowired-controllers-as-services-for-lazy-people.md, source/_posts/2016/2016-07-18-forget-autowire-just-use-it.md
Based on https://github.com/Symplify/Symplify/pull/162
=> [blog] deprecate default autowire

source/_posts/2016/2016-02-25-modular-routing-in-symfony.md
Ref: https://github.com/Symplify/Symplify/pull/182
=> [blog] deprecate routing

source/_posts/2017/2017-06-17-php-object-calisthenics-rules-made-simple-version-3-0-is-out-now.md
=> Replace `else` rules example

source/_layouts/post.latte, source/_snippets/post/postYouMightAlsoLike.latte
Testing in practise to check the relevance level will follow on website daily usage.
=> [blog] Add Similar posts section

source/_posts/2015/2015-11-09-4-zhave-novinky-v-symfony-3.md, source/_posts/2015/2015-12-20-to-nejlepsi-ze-symfonyconu-2015.md, source/_posts/2016/2016-03-03-kolik-lidi-je-potreba-k-vytvoreni-jedne-komunity.md, source/_posts/2016/2016-09-09-how-to-write-open-source-in-php-1-create-a-repository.md, source/_posts/2016/2016-09-16-how-to-write-open-source-in-php-2-enjoy-skeletons.md, source/_posts/2016/2016-09-26-symfony-komunita-roste-na-pehapkare-a-otevira-se-vsem-php-programatorum.md, source/_posts/2016/2016-12-24-how-to-avoid-inject-thanks-to-decorator-feature-in-nette.md, source/_posts/2017/2017-01-05-why-I-deleted-my-linkedin-account.md, source/_posts/2017/2017-01-20-4-emotional-reasons-why-I-quit-my-twitter.md, source/_posts/2017/2017-01-31-how-monolithic-repository-in-open-source-saved-my-laziness.md, source/_posts/2017/2017-02-07-how-to-decouple-monolith-like-a-boss-with-composer-local-packages.md, source/_posts/2017/2017-02-12-drop-all-service-tags-in-your-nette-and-symfony-applications.md, source/_posts/2017/2017-02-15-minimalistic-way-to-create-your-first-nette-extension.md, source/_posts/2017/2017-02-20-statie-how-to-run-it-locally.md, source/_posts/2017/2017-03-02-php-u-nas-ceka-rok-expanze.md, source/_posts/2017/2017-03-06-statie-2-how-to-add-contact-page-with-data.md, source/_posts/2017/2017-03-09-statie-3-how-to-add-reusable-parts-of-code.md, source/_posts/2017/2017-03-13-statie-4-how-to-create-the-simplest-blog.md, source/_posts/2017/2017-05-03-combine-power-of-php-code-sniffer-and-php-cs-fixer-in-3-lines.md, source/_posts/2017/2017-05-07-how-to-refactor-to-new-dependency-injection-features-in-symfony-3-3.md, source/_posts/2017/2017-05-29-symplify-packages-deprecations-brought-by-symfony-33.md, source/_posts/2017/2017-06-19-symbiotic-controller-nette-presenter-with-freedom.md, source/_posts/2017/2017-06-26-php-object-calisthenics-rules-made-simple-version-3-0-is-out-now.md, source/_posts/2017/2017-07-03-how-to-deprecate-php-package-without-leaving-anyone-behind.md, source/_posts/2017/2017-07-17-how-to-write-custom-sniff-for-code-sniffer-3.md, source/_posts/2017/2017-07-24-how-to-write-custom-fixer-for-php-cs-fixer-24.md, source/_posts/2017/2017-07-31-how-php-coding-standard-tools-actually-work.md
=> add few related posts

source/assets/css/style.css, source/contact.latte
=> add feedback form to contact, highlight phone and email

source/_posts/2017/2017-10-02-easy-coding-standard-and-phpstan-meet-3-symfony-ecommerce-projects.md
Shopsys Framework has no more PSR-2 violations than Sylius, actually it has zero
=> Update PSR-2 takeaway for Shopsys Framwork

composer.json, easy-coding-standard.neon, source/_posts/2017/2017-09-18-4-simple-checkers-for-coding-standard-haters-but-clean-code-lovers.md, src/TweetPublisher/Exception/TweetImageNotFoundException.php, src/TweetPublisher/PostTweetsProvider.php, src/TweetPublisher/PostsProvider.php, src/TweetPublisher/TweetPublisher.php, src/TweetPublisher/TwitterApi/TwitterApiWrapper.php, src/TweetPublisher/config/config.neon
Closes #178 
Just type relative URL to image.
```yaml
tweet: "Some Tweet"
tweet_image: "assets/images/posts/2017/clean-checkers/dependency-drop.png"
```
=> [TweetPublisher] improvements

source/_data/talks.neon, source/_snippets/menu.latte, source/assets/css/style.css, source/contact.latte, source/mentoring-and-lectures.latte, source/talks.latte, statie.neon
=> [mentoring] made nicer + [video] init

source/_posts/2017/2017-03-13-statie-4-how-to-create-the-simplest-blog.md
In actual version of Statie you have to configure `post_route` in `statie.neon`
=> Fix post_route configuration description

.coveralls.yml, .travis.yml, README.md, composer.json, phpunit.xml, source/_posts/2017/2017-10-30-what-can-you-learn-from-menstruation-and-symfony-releases.md, src/Posts/Year2017/Ast/SomeClass.php, tests/Posts/Year2017/Ast/ModifyTest.php
- add Travis stages
- init simple `nikic/php-parser` test
=> Tested post setup

source/_posts/2017/2017-12-17-new-in-symplify-3-doc-block-cleaner-fixer.md, source/_snippets/menu.latte, source/assets/css/style.css, source/index.latte
Thanks for inspiration at vzhurudolu by @michdev
=> Restyle healdines

source/_snippets/post/postMetadataLine.latte, source/assets/css/style.css
=> make post metadata less attention stealing

composer.json, source/_posts/2018/2018-02-03-how-to-run-symfony-processes-asynchronously.md, source/_posts/2018/2018-02-05-how-to-run-symfony-processes-asynchronously.md, src/Posts/Year2018/ProcessAsync/ProcessesInParallel.php, tests/Posts/Year2018/ProcessAsync/ProcessesInParallelTest.php
Based on https://github.com/Symplify/Symplify/pull/620
=> [post] async process post added

source/_posts/2018/2018-02-05-how-to-run-symfony-processes-asynchronously.md
=> Remove obsolete char

source/_posts/2018/2018-03-26-new-easy-coding-standard-4-clean-symfony-standard-with-yaml-and-services.md
Or if you meant it is released but still in alpha I propose removing brackets.
=> Is it typo?

composer.json, easy-coding-standard.yml, source/_posts/2017/2017-03-06-statie-2-how-to-add-contact-page-with-data.md, source/_posts/2017/2017-03-09-statie-3-how-to-add-reusable-parts-of-code.md, source/_posts/2017/2017-03-13-statie-4-how-to-create-the-simplest-blog.md, source/_posts/2017/2017-05-03-combine-power-of-php-code-sniffer-and-php-cs-fixer-in-3-lines.md, source/_posts/2017/2017-06-26-php-object-calisthenics-rules-made-simple-version-3-0-is-out-now.md, source/_posts/2017/2017-07-17-how-to-write-custom-sniff-for-code-sniffer-3.md, source/_posts/2017/2017-07-24-how-to-write-custom-fixer-for-php-cs-fixer-24.md, source/_posts/2017/2017-08-07-7-new-features-in-easy-coding-standard-22.md, source/_posts/2017/2017-08-21-5-useful-rules-from-symplify-coding-standard.md, source/_posts/2017/2017-09-18-4-simple-checkers-for-coding-standard-haters-but-clean-code-lovers.md, source/_posts/2017/2017-10-02-easy-coding-standard-and-phpstan-meet-3-symfony-ecommerce-projects.md, source/_posts/2017/2017-12-11-new-in-symplify-3-statie-generators.md, source/_posts/2017/2017-12-17-new-in-symplify-3-doc-block-cleaner-fixer.md, source/_posts/2018/2018-01-01-new-in-symplify-3-4-time-saving-coding-standard-checkers.md, source/_posts/2018/2018-03-12-neon-vs-yaml-and-how-to-migrate-between-them.md, source/_posts/2018/2018-03-26-new-in-easy-coding-standard-4-clean-symfony-standard-with-yaml-and-services.md
Ref https://github.com/Symplify/Symplify/issues/665
=> [posts] bump to Symplify 4

source/index.latte
Search on blog is crutial. Setup? 15 minutes. Effect? Limitless :rocket: 
When allowed Algolia Docs, possibly improve
=> add simple Google search, to be able to find inside posts

source/_data/projects.yml, source/_data/talks.yml, source/about.latte, statie.yml
=> add projects

easy-coding-standard.yml, source/_data/generators.yml, source/_data/projects.yml, source/_posts/2015/2015-11-09-4-zhave-novinky-v-symfony-3.md, source/_posts/2015/2015-12-20-to-nejlepsi-ze-symfonyconu-2015.md, source/_posts/2016/2016-12-09-jak-se-vyporadat-s-hejty-v-komentarich.md, source/_posts/2017/2017-01-10-jak-psat-zajimave-inzeraty-pro-ajtaky.md, source/_posts/2017/2017-09-15-4-simple-checkers-for-coding-standard-haters-but-clean-code-lovers.md, source/_posts/2017/2017-11-06-wow-to-change-php-code-with-abstract-syntax-tree.md, source/_posts/2018/2018-04-23-how-to-slowly-turn-your-symfony-project-to-legacy-with-action-injection.md, source/about.latte, source/assets/css/style.css, src/Statie/Exception/MissingIdException.php, src/Statie/Generator/PostFileSorter.php, statie.yml
=> Intro post project

source/_posts/2018/2018-04-26-how-i-got-into-static-trap-and-made-fool-of-myself.md
=> [post] How I Got into Static Trap and Made Fool of Myself

source/_posts/2018/2018-04-26-how-i-got-into-static-trap-and-made-fool-of-myself.md
In the sentence "It might be a small deal for performance, but even bigger for legacy code smell that would just me back" there's apparently a verb missing, but I didn't figure out what you meant so I supplied none.
=> Fix some typos

composer.json, phpstan.neon, source/_data/generators.yml, source/_layouts/post.latte, source/_posts/2017/2017-01-15-7-rad-ktere-bych-si-dal-pred-odchodem-na-vysokou-skolu.md, source/_posts/2017/2017-10-16-how-to-use-repository-with-doctrine-as-service-in-symfony.md, source/_posts/2018/2018-04-26-how-i-got-into-static-trap-and-made-fool-of-myself.md, src/Statie/Exception/DuplicatedIdException.php, src/Statie/Generator/PostFileSorter.php
=> Add Rectify interlink

source/_posts/2018/2018-04-30-programming-climbing-a-huge-mountain.md
Thank you for the article btw :)
=> Fix a few typos

source/_posts/2018/2018-05-14-how-to-load-config-with-services-in-symfony-console.md
Remove localhost from the link
=> Fix link to another post

source/_snippets/footer.latte, source/about.latte, source/assets/css/style.css, source/index.latte
=> blog: narrow 4+ post

easy-coding-standard.yml, source/_posts/2018/2018-06-04-how-to-migrate-from-php-code-sniffer-to-easy-coding-standard.md, source/_posts/2018/2018-06-07-how-to-migrate-from-php-cs-fixer-to-easy-coding-standard.md
=> [post] php-cs-fixer to ECS

source/_posts/2018/2018-06-11-how-to-turn-mocks-from-nightmare-to-solid-kiss-tests.md
=> [post] nomock init

source/_posts/2018/2018-06-11-how-to-turn-mocks-from-nightmare-to-solid-kiss-tests.md, source/_posts/2018/2018-06-14-collector-pattern-for-dummies.md
=> [post] Collector minimalistic

composer.json, source/_posts/2018/2018-05-03-how-do-you-treat-your-own-first-ai.md, source/_snippets/post/postMetadataLine.latte
Every post with 3+ more code snippets is now marked with "code". So reader can pick theory or code, based on needs.
Closes #368
=> add code badge

source/_data/talks.yml, source/talks.latte
=> Improve Talks

source/_snippets/head.latte, source/assets/css/checklist.css, source/assets/css/style.css, source/little-books.latte
=> Style bookies checklist

source/_posts/2018/2018-06-14-collector-pattern-for-dummies.md
=> collector-pattern-for-dummies : replace UnitedKindom by UnitedKingdom

source/_posts/2018/2018-06-21-open-source-is-selfish.md
=> [post] selfish opensource

source/_posts/2018/2018-01-15-is-your-changelog-useful-or-just-boring-plain-text-and-how-to-fix-that.md, source/_posts/2018/2018-06-25-let-changelog-linker-generate-changelog-for-you.md
=> [post] changelog linker

source/_posts/2018/2018-06-21-open-source-is-selfish.md
=> copy edits

source/_posts/2018/2018-01-15-is-your-changelog-useful-or-just-boring-plain-text-and-how-to-fix-that.md, source/_posts/2018/2018-07-02-cluster-more-interactive-than-book-deeper-than-post.md
=> update changelog linker with run command

source/_snippets/post/postYouMightAlsoLike.twig
=> [post] improve related post preview

composer.json, source/_posts/2018/2018-07-05-how-to-convert-latte-templates-to-twig-in-27-regular-expressions.md, source/_snippets/post/postMetadataLine.twig, tests/Posts/Year2018/LatteTwig/LatteToTwigConverterTest.php, tests/Posts/Year2018/LatteTwig/Source/expected-twig-file.twig, tests/Posts/Year2018/LatteTwig/Source/latte-file.latte
=> [test] Add Latte Twig post test

source/_data/clusters.yml, source/_posts/2018/2018-07-16-new-in-statie-45-twig-support.md, source/clusters.twig
=> Improve Clusters

source/_posts/2018/2018-07-26-why-is-your-company-losing-money-by-not-open-sourcing-1-hiring.md, source/assets/css/style.css, source/contact.twig, source/mission.twig
=> Improve mission

source/_posts/2018/2018-04-26-how-i-got-into-static-trap-and-made-fool-of-myself.md
=> 2018-04-26: correct swapped code examples

source/_posts/2018/2018-08-16-whats-new-in-php-73-in-30-seconds-in-diffs.md
=> [post] PHP 7.3 init

source/_posts/2018/2018-08-16-whats-new-in-php-73-in-30-seconds-in-diffs.md
Pull request after your comment
https://disqus.com/home/discussion/itsworthsharing/whats_new_in_php_73_in_30_seconds_in_diffs/#comment-4051608077
=> Fix link in paragraph #4

source/_posts/2018/2018-08-27-why-and-how-to-avoid-the-memory-lock.md
=> init memory lock post

source/assets/css/style.css, source/index.twig
=> make header clear

source/_posts/2018/2018-06-18-14-surprising-tip-from-selling-is-human-to-influence-others.md
=> Fix `to` --> `too`

source/_posts/2017/2017-02-07-how-to-decouple-monolith-like-a-boss-with-composer-local-packages.md
Changed from `packages/Lekarna/Filesystem` to `packages/lekarna/filesystem`
=> case sensitive ?

source/_posts/2016/2016-08-15-podcast-o-php-a-sebevzdelavani.md, source/_posts/2018/2018-03-26-new-easy-coding-standard-4-clean-symfony-standard-with-yaml-and-services.md, source/_posts/2018/2018-09-17-7-tips-to-write-exceptions-everyone-will-love.md, source/assets/css/style.css
=> post exception

source/_posts/2017/2017-02-20-statie-how-to-run-it-locally.md, source/_posts/2017/2017-03-06-statie-2-how-to-add-contact-page-with-data.md, source/_posts/2017/2017-03-09-statie-3-how-to-add-reusable-parts-of-code.md, source/_posts/2017/2017-03-13-statie-4-how-to-create-the-simplest-blog.md, source/_posts/2017/2017-12-11-new-in-symplify-3-statie-generators.md, source/_posts/2018/2018-07-16-new-in-statie-45-twig-support.md
=> Statie posts bump

source/_posts/2018/2018-09-27-new-in-symplify-5-create-merge-and-split-monorepo-with-1-command.md
Probably that keyboard need a replacement ;-)
=> Another one coposer.json --> composer.json

source/_posts/2018/2018-10-04-new-in-symplify-5-public-method-order-and-external-final-in-coding-standard.md, source/assets/css/style.css, source/clusters.twig, source/index.twig, source/mission.twig, source/talks.twig
=> Don't make me think

source/assets/css/style.css, source/clusters.twig, source/talks.twig
=> make menu step-out, few misc

source/_posts/2018/2018-04-12-the-best-5-of-256-bloghacks-book.md
We are a little slow answering question but not enough to call us "Overlow"
=> StackOverlow > StackOverflow

.travis.yml, packages/ContribThanker/src/Command/DumpContributorsCommand.php, source/thank-you.twig
=> "Thank you" Improvements

packages/ContribThanker/src/Api/GithubApi.php, packages/ContribThanker/src/Twig/ContribThankerFilterProvider.php, source/_data/contributors.yml, source/thank-you.twig, statie.yml
=> make thank you nicer

source/_posts/2017/2017-10-02-easy-coding-standard-and-phpstan-meet-3-symfony-ecommerce-projects.md
Change `compatble` to `compatible`
=> Fix typo in article

source/_data/clusters.yml, source/_posts/2018/2018-11-05-do-you-autowire-services-in-symfony-you-can-autowire-parameters-too.md
=> [post] autowire params

source/_posts/2018/2018-11-15-how-to-get-php-74-typed-properties-to-your-code-in-few-seconds.md, source/_posts/2018/2018-11-19-when-you-should-use-monorepo-and-when-local-packages.md, source/_snippets/footer.twig, source/clusters.twig
=> [post] monorepo x packages

source/_data/clusters.yml, source/_posts/2018/2018-11-22-how-to-test-monorepo-in-3-layers.md
=> post: monorepo testing

source/_posts/2018/2018-12-06-dont-learn-to-code.md
=> post-dont learn to code

source/_posts/2017/2017-05-07-how-to-refactor-to-new-dependency-injection-features-in-symfony-3-3.md
Related to https://github.com/symplify/autodiscovery package
=> simplify autodiscovery post

ide-twig.json, source/_posts/2017/2017-05-07-how-to-refactor-to-new-dependency-injection-features-in-symfony-3-3.md, source/_posts/2018/2018-12-27-how-to-convert-all-your-symfony-service-configs-to-autodiscovery.md
=> Update Autodiscovery posts

composer.json, source/_posts/2019/2019-01-10-9-steps-to-migrate-from-jekyll-to-statie.md
=> [post] 9 steps - jekyll to statie

source/_posts/2019/2019-01-14-11-steps-to-migrate-from-sculpin-to-statie.md
=> [post] sta-sculp migrate

source/_posts/2019/2019-01-24-how-to-kill-parents.md
=> [Post] Fix typos and php code samples in Kill Parents post

source/_posts/2019/2019-02-07-what-i-learned-by-using-thecodingmachine-safe.md
Closes #653 
There you go @akondas :)
=> add safe post

source/_posts/2019/2019-02-25-5-tips-to-effective-work-with-github-repository.md
A program cannot be sexy. Secretaries are not always female or sexy. The best secretaries are not good because they are sexy.
=> Remove unnecessary word

source/_posts/2018/2018-08-20-painful-experience-over-solutions-extend-configuratin-in-easy-admin-bundle-with-collector.md
did I get it right? :thinking:
=> Refactor sentence about AI & screwed humanity

source/_posts/2018/2018-05-31-symfony-vs-laravel-vs-nette-which-php-framework-you-should-choose.md, source/_posts/2019/2019-03-11-why-we-migrated-from-nette-to-symfony-in-3-weeks-part-3.md, source/assets/css/style.css, source/clusters.twig
=> redesign clusters

source/_data/future_talks.yaml, source/_layouts/post.twig, source/_snippets/post/post_metadata_line.twig, source/assets/css/style.css, source/clusters.twig, source/czech-posts.twig, source/index.twig
=> add meet me

source/_data/generated/php_framework_trends.yaml, source/_posts/2019/2019-04-11-trends-of-php-frameworks-in-numbers.md, source/_snippets/future_talks.twig, source/php-framework-trends.twig, src/Command/GeneratePackageStatsCommand.php, src/Packagist/PackageMonthlyDownloadsProvider.php, src/Packagist/VendorPackagesProvider.php
Based on https://www.tomasvotruba.cz/blog/2019/04/11/trends-of-php-frameworks-in-numbers/#comment-4420318730
Thank you @garas
---
Based on https://www.tomasvotruba.cz/php-framework-trends/#comment-4419584311
Thank you @nojimage
=> "PHP Framework Trends" Corrections for CakePHP and Laravel

source/_data/generated/php_framework_trends.yaml, source/php-framework-trends.twig, src/Command/GeneratePackageStatsCommand.php, src/Statistics.php
Remove invalid cases like this: https://packagist.org/packages/symfony/security-csrf/stats
=> [php fw trends] remove newly added interdependency

config/parameters.yaml, ecs.yaml, phpstan.neon, source/_data/generated/vendor_packages_by_version.yaml, source/package-downloads-by-version.twig, source/php-framework-trends.twig, src/ArrayUtils.php, src/Command/GeneratePackageStatsCommand.php, src/Command/GeneratePackageStatsGroupedByVersionCommand.php, src/Packagist/MinorPackageVersionsDownloadsProvider.php, src/Result/PackageDataFactory.php, src/Result/PackageDataGroupedByVersionFactory.php, src/Result/VendorDataFactory.php, statie.yaml
=> [php fw trends] Add package downloads by version - major and minor

source/_posts/2018/2018-05-17-how-to-test-private-services-in-symfony.md, source/_posts/2018/2018-10-22-brief-history-of-tools-watching-and-changing-your-php-code.md, source/_posts/2018/2018-11-29-how-to-manage-configuration-in-symfony-without-bundle-extension-and-configuraiton.md, source/assets/css/style.css
=> Update various post

source/_posts/2019/2019-04-22-hidden-gems-of-php-packages-srab.md
=> [post] gems srab

source/_layouts/post.twig
=> Fixed tiny typo

source/_posts/2019/2019-04-22-hidden-gems-of-php-packages-srab.md, source/_posts/2019/2019-04-25-don-t-give-up-your-php-code-for-compiler-passes-so-easily.md
=> [post] compiler pass

source/_posts/2019/2019-04-22-hidden-gems-of-php-packages-srab.md
I will try it on our "spaghetti al dente" project some day, TY for article as always :smiley:
=> Minor typo :)

source/index.twig, source/updated-posts.twig, src/Twig/SortUpdatedPostByFilterProvider.php
=> Add updated posts page

source/_posts/2019/2019-04-29-rector-european-tour-in-may-june-2019.md
Not sure which response suites you better, but probably one should be removed :)
=> Duplication of my response

source/_data/generated/php_framework_trends.yaml, source/_data/generated/testing_packages.yaml, source/_data/generated/vendor_packages_by_version.yaml
Monthly update
```
vendor/bin/statie generate-package-stats
vendor/bin/statie generate-package-stats-grouped-by-version
vendor/bin/statie generate-testing-package-stats
```
=> [stats] Update trends for frameworks 2019/05

source/_posts/2019/2019-05-13-hidden-gems-of-php-packages-psalm-fixing-your-code.md
=> [post] psatic

source/assets/css/style.css, source/contact.twig
closes #782
Inspired by https://www.amazon.com/Digital-Minimalism-Choosing-Focused-Noisy/dp/0525536515
=> add contact time

source/_layouts/post.twig, source/_posts/2019/2019-01-10-9-steps-to-migrate-from-jekyll-to-statie.md, source/_snippets/post/post_archive.twig, source/_snippets/post/post_metadata_line.twig, source/archive/2016.twig, source/archive/2017.twig, source/archive/2018.twig, source/index.twig, statie.yaml
=> Improve Dom

source/_posts/2019/2019-05-13-hidden-gems-of-php-packages-psalm-fixing-your-code.md
https://psalm.dev/docs/fixing_code/#possiblyundefinedvariable
=> Use correct psalm issue for alternation

config/parameters.yaml, source/_data/generated/php_framework_trends.yaml, source/_data/generated/vendor_packages_by_version.yaml
- https://www.tomasvotruba.cz/php-framework-trends/
=> [Stats] Update for 2019-06 + Doctrine project added

source/_data/talks_feedback.yaml, source/assets/css/style.css, source/talks.twig, src/Twig/TalksCountFilterProvider.php
=> Add Quotes for talks

source/_posts/2019/2019-06-20-7-news-and-changes-in-symplify-6.md, source/assets/css/style.css
=> [post] add Symplify 6 news

config/parameters.yaml, phpstan.neon, source/_data/generated/php_framework_trends.yaml, source/_data/generated/vendor_packages_by_version.yaml, source/_posts/2019/2019-07-29-how-we-completed-thousands-of-missing-var-annotations-in-a-day.md, source/_snippets/macros/trends_macros.twig, source/_snippets/menu.twig, source/package-downloads-by-version.twig, src/Command/GeneratePackageStatsGroupedByVersionCommand.php, src/Packagist/MinorPackageVersionsDownloadsProvider.php, src/Packagist/PackageVersionPublishDatesProvider.php, src/Result/PackageDataGroupedByVersionFactory.php, src/Twig/NumberFilterProvider.php
https://www.tomasvotruba.cz/package-downloads-by-version/
=> Improve PHP Framework stats by version

composer.json, source/_data/generated/php_framework_trends.yaml, source/php-framework-trends.twig, src/Result/VendorDataFactory.php, src/VersionManipulator.php
Average trends were pretty skewish, creating fake info
=> rebuild trends by absolute numbers

source/_posts/2019/2019-10-28-all-you-always-wanted-to-know-about-monorepo-but-were-afraid-to-ask.md
Deprecating own domain at http://github.com/TomasVotruba/gomonorepo.org
=> [post] add go monorepo

source/_data/generated/php_framework_trends.yaml, source/_posts/2018/2018-04-02-rectify-turn-repositories-to-services-in-symfony.md
Closes #https://github.com/rectorphp/rector/issues/2212
=> Update stats 2019 10

source/_posts/2017/2017-08-07-7-new-features-in-easy-coding-standard-22.md, source/_posts/2018/2018-04-09-try-psr-12-on-your-code-today.md, source/_posts/2018/2018-05-14-how-to-load-config-with-services-in-symfony-console.md, source/_posts/2018/2018-06-04-how-to-migrate-from-php-code-sniffer-to-easy-coding-standard.md, source/_posts/2018/2018-06-07-how-to-migrate-from-php-cs-fixer-to-easy-coding-standard.md, source/_posts/2018/2018-09-17-7-tips-to-write-exceptions-everyone-will-love.md
See https://github.com/Symplify/Symplify/pull/1663/
=> change --level in ECS to --set

source/_posts/2017/2017-02-20-statie-how-to-run-it-locally.md, source/_posts/2018/2018-07-05-how-to-convert-latte-templates-to-twig-in-27-regular-expressions.md, source/_posts/2018/2018-07-16-new-in-statie-45-twig-support.md, source/_posts/2019/2019-01-10-9-steps-to-migrate-from-jekyll-to-statie.md, source/_posts/2019/2019-11-18-how-to-delegate-code-reviews-to-ci.md
See https://github.com/Symplify/Symplify/pull/1641
=> Statie mention Latte drop

source/_posts/2019/2019-10-28-all-you-always-wanted-to-know-about-monorepo-but-were-afraid-to-ask.md
Changed a typo in the title: 'affraid' to 'afraid'
=> Fixed a typo

source/_posts/2019/2019-11-25-the-single-best-skill-to-master-command-line.md
=> [post] shortcuts

source/_posts/2019/2019-12-02-how-to-box-symfony-app-to-phar-without-killing-yourself.md
Post mostly about https://github.com/rectorphp/rector/pull/2373
=> [post] add symfony-phar

source/_posts/2019/2019-12-09-how-to-get-rid-of-technical-debt-or-what-we-would-have-done-differently-2-years-ago.md
From „PHPUnit fill find them“ to „PHPUnit will find them“
=> Fix minor spelling from „fill find“ to „will find“

source/_posts/2020/2019-12-30-doctrine-behaviors-2-0-reloaded.md
Fix bad link - it should point to pehapkari.cz.
=> Fix bad link

source/_posts/2019/2019-01-03-how-to-complete-type-declarations-without-docblocks-with-rector.md
Changed Rector\Php\Rector\FunctionLike\ReturnTypeDeclarationRector to the new Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector class
=> Changed ReturnTypeDeclarationRector class

source/_posts/2020/2020-02-17-local-packages-3-years-later.md
=> [post] local packages 3 years later

source/_posts/2020/2020-03-02-we-do-not-need-senior-developers-we-need-senior-code-bases.md
Fixed some typos, wording, and fixed "codebase" vs "code base" consistency.
=> Minor improvements to "We Do Not Need Senior Developers"

config/packages/twig.yaml, packages/blog/config/data/2017/2017-02-20-statie-how-to-run-it-locally.md, packages/blog/config/data/2017/2017-03-09-statie-3-how-to-add-reusable-parts-of-code.md, packages/blog/config/data/2017/2017-03-13-statie-4-how-to-create-the-simplest-blog.md, packages/blog/config/data/2017/2017-12-11-new-in-symplify-3-statie-generators.md, packages/blog/config/data/2018/2018-07-16-new-in-statie-45-twig-support.md, packages/blog/config/data/2019/2019-01-07-how-to-create-your-first-php-twig-static-website-under-2-minutes-with-statie.md, packages/blog/config/data/2019/2019-01-14-11-steps-to-migrate-from-sculpin-to-statie.md, packages/blog/config/data/2019/2019-01-17-how-writing-posts-helps-you-to-become-better-programmer.md, templates/blog/post.twig
Use https://github.com/symplify/symfony-static-dumper instead
=> deprecate Statie posts

packages/blog/config/data/2020/2020-03-02-we-do-not-need-senior-developers-we-need-senior-code-bases.md
Hi 👋 Thank you for a great article, I enjoyed it! I spotted a few weak spots in the writing, and I thought I could contribute to your blog by sending this PR proposing a few improvements. Keep up the good work, happy coding to you too!
=> Improvements to wording, fixes of typos

config/_data/generated/php_framework_trends.yaml
=> update stats for 2020/03

config/_data/generated/php_framework_trends.yaml
=> [stats] update for 2020/04

packages/blog/config/data/2020/2020-05-18-the-future-of-pehapkari-meetups-and-trainings-you.md
After almost a year having this in my mind, I dedicated time to put it words.
I need feedback on this, so this message is clear:
- community works and is pretty good
- my priorities have changed elsewhere
- if you want to continue meetups & trainings, let me know, I'll pass it to you
=> [post] growing pehapkari futher

config/_data/generated/php_framework_trends.yaml, packages/framework-stats/src/Packagist/PackageRawMonthlyDownloadsProvider.php
=> update framework stats for 2020/05

packages/blog/config/data/2019/2019-12-23-5-things-i-improve-when-i-get-to-new-repository.md
=> Fix a typo in a post

config/_data/generated/php_framework_trends.yaml
=> update stats for 2020/07

packages/blog/config/data/2020/2020-06-22-why-class-constants-should-be-typed.md
Small typo fixes :
- Removed extra "the" article.
- Fix some plurals
=> Small typo fixes

config/_data/generated/php_framework_trends.yaml
=> update stats for 2020_08

packages/blog/config/data/2020/2020-08-31-how-static-methods-kills-you-like-corona.md
Hello @TomasVotruba 
First, I would like to thanks you for your blog and all excellent articles we can read. Very useful and good explains !
Second, I've noticed very minor typo error in "How Static Methods Kill You Like Corona" article.
=> Corona static - fix typo error

composer.json, config/config.php, public/assets/css/style.css, src/Controller/ProjectsController.php, src/Exception/ShouldNotHappenException.php, src/ValueObject/PackagistPackage.php, symfony.lock, templates/_snippets/menu.twig, templates/projects/projects.twig
Packagest details by https://github.com/spatie/packagist-api
=> [Projects] new page

.github/workflows/code_analysis.yaml, .github/workflows/refresh_framework_stats.yaml, ecs.php
Closes https://github.com/TomasVotruba/tomasvotruba.com/issues/1074
- [ci] add refresh framework stats autogenerated job
- fixup! [ci] add refresh framework stats autogenerated job
- [ci] add current date
=> [CI] Add Gitub Actoins Rebuild stats every month

packages/blog/config/data/2019/2019-03-14-remove-dead-public-methdos-from-your-code.md
maybe you should have some kind of github action which checks all posts regarding outgoing links and there http status?
e.g. https://github.com/tcort/markdown-link-check (never used it myself, though)
=> fixed dead link

packages/blog/data/2021/2021-01-11-how-to-detect-complex-duplicated-methods-with-phpstan.md
Closes https://github.com/TomasVotruba/tomasvotruba.com/issues/1132
=> [post] duplicate code

config/packages/twig.php, config/routes.php
Closes https://github.com/TomasVotruba/tomasvotruba.com/issues/1140
=> add missing cleaning-lady-checklist page

packages/blog/data/2019/2019-05-16-don-t-ever-use-listeners.md
...and some typos. At least, I'm *guessing* that "constant list" was a typo too...
=> Removing duplicate code sample

packages/blog/src/ValueObject/Post.php, templates/_snippets/post/post_metadata_line.twig
Closes https://github.com/TomasVotruba/tomasvotruba.com/issues/1161
=> [design] remove reading time

packages/blog/data/2021/2021-05-17-rector-the-power-of-automated-refactoring-book-released.md
Ref https://leanpub.com/rector-the-power-of-automated-refactoring
https://matthiasnoback.nl/2021/05/early-release-of-the-rector-book/
=> [post] release book

packages/blog/data/2021/2021-05-31-how-to-refactor-custom-doctrine-annotations-to-attributes.md
Ref https://github.com/apitte/core/issues/151
=> [post] anno to attr

packages/blog/data/2021/2021-06-03-how-i-redesigned-my-website-the-way-i-refactor-legacy-projects.md
=> Set same Title as Slug

.github/workflows/rector.yaml, composer.json, packages/blog/data/2018/2018-11-05-do-you-autowire-services-in-symfony-you-can-autowire-parameters-too.md, packages/blog/data/2021/2021-06-07-why-should-we-talk-about-our-mitakes-in-php-community.md, packages/blog/src/ValueObjectFactory/PostFactory.php, phpstan.neon, symfony.lock
Ref https://github.com/TomasVotruba/tomasvotruba.com/issues/1202 - 1st part
=> [post] why should we share mistakes as #php community

packages/blog/data/2021/2021-07-05-why-do-we-scope-php-tools.md, packages/blog/data/2021/2021-07-08-how-to-scope-your-php-tool-in-10-steps.md
Sharing experience from https://github.com/symplify/symplify/issues/3388#issuecomment-875301853
For future generations and my forgetful brain :)
=> tv post downgrade

composer.json, public/assets/css/style.css, templates/trainings/trainings.twig
See https://github.com/TomasVotruba/tomasvotruba.com/issues/1213
<br>
=> [trainigs] Add CI + PHPStan trainings

ecs.php, packages/blog/data/2021/2021-06-28-how-to-replace-single-node-with-two-nodes-in-abstract-syntax-tree.md, packages/blog/src/ValueObject/Post.php, packages/blog/src/ValueObjectFactory/PostFactory.php, packages/tweeter/src/Command/PublishedTweetsCommand.php, packages/tweeter/src/Command/TweetCommand.php, packages/tweeter/src/TweetFilter/PublishedTweetsFilter.php, packages/tweeter/src/TweetProvider/PublishedPostTweetsProvider.php, packages/tweeter/src/TwitterApi/TwitterPostApiWrapper.php, packages/tweeter/src/ValueObject/PublishedTweet.php, packages/tweeter/src/ValueObjectFactory/PublishedTweetFactory.php, src/ValueObject/Option.php
- remove duplicate rule
- cleanup username that breaks the linked url
=> Twitter fix false positive on published tweets

packages/blog/data/2021/2021-07-19-launching-3-trainings-rector-phpstan-and-bulletproof-ci.md, templates/trainings/trainings.twig
Closes  https://github.com/TomasVotruba/tomasvotruba.com/issues/1213
- misc
- [post] trainigns
- gram
=> [post] launch training

packages/blog/data/2019/2019-04-11-trends-of-php-frameworks-in-numbers.md, packages/blog/data/2021/2021-07-26-how-i-made-huge-mistake-with-interpretation-of-laravel-downloads.md, packages/blog/data/2021/2021-07-26-sunsetting-php-framework-trends.md
- [post] sunsetting php fw trends
- gram + emo
Ref https://github.com/tomasvotruba/phpfwtrends.org
<br>
Closes https://github.com/TomasVotruba/phpfwtrends.org/issues/26
=> [post] sunsetting phpfwtrends

composer.json, ecs.php, phpstan.neon
- bump ECS to 16x faster one
- remove fixed phpstan errors
- bump
- hotfix of missing dep
=> Bump ECS to 16x faster one 🥳️🥳️🥳️

composer.json, rector.php
- [rector] enable parallel
- update composer.json to 2.2
=> [rector] enable parallel

packages/blog/data/2019/2019-03-21-how-to-instantly-migrate-phpspec-to-phpunit.md, packages/blog/data/2019/2019-03-25-how-to-instantly-migrate-nette-tester-to-phpunit.md
Ref https://github.com/rectorphp/rector-src/pull/1901
=> [post] Deprecated phpspec rector set

packages/blog/data/2019/2019-03-21-how-to-instantly-migrate-phpspec-to-phpunit.md, packages/blog/data/2019/2019-03-28-how-to-mock-final-classes-in-phpunit.md, packages/blog/data/2019/2019-07-29-how-we-completed-thousands-of-missing-var-annotations-in-a-day.md
- Update PHPUnit fixtures to be correct syntax.
=> Update PHPUnit fixtures to be correct syntax

composer.json, ecs.php, rector.php
- bump to Symplify 10.2
- use new ECSConfig
=> Make use of ECSConfig 🥚

packages/blog/data/2019/2019-03-28-how-to-mock-final-classes-in-phpunit.md
=> Resolve issue #1299

packages/blog/data/2022/2022-05-19-5-steps-to-get-ready-for-latte-3.md
Ref:
* https://forum.nette.org/cs/35141-latte-3-nejvetsi-vyvojovy-skok-v-dejinach-nette
* https://github.com/nette/latte/releases/tag/v3.0.0
=> [post] 5 steps to get ready to latte 3

packages/blog/data/2022/2022-07-25-how-to-develop-sole-package-in-php81-and-downgrade-to-php72.md, phpstan.neon, rector.php
- [post] sole package downgrade
- gram
- note
=> [post] downgrade package php72

.env, .env.local, .gitignore, packages/blog/src/Repository/PostRepository.php
To avoid conflict in server when deploy. I created `.env.local` for local template.
=>  register .env to .gitignore 

composer.json, packages/blog/src/ValueObject/Post.php, packages/blog/src/ValueObjectFactory/PostFactory.php, rector.php, resources/views/book/books.blade.php, resources/views/homepage.blade.php, src/Controller/BookDetailController.php, src/ValueObject/Book.php
- mics
- remove unuesd string, markdown deps
=> tv tidy deps

.gitignore, composer.lock
composer.lock should not be ignored on project, as in server, it will run composer install, without `composer.lock` commited, on server, it can broke anytime without tested first in CI.
=> Do not ignore composer.lock

app/Http/Controller/AboutController.php, app/Http/Controller/BlogController.php, app/Http/Controller/BookDetailController.php, app/Http/Controller/BooksController.php, app/Http/Controller/ContactController.php, app/Http/Controller/HomepageController.php, app/Http/Controller/PostController.php, app/Http/Controller/PostImageController.php, app/Http/Controller/RssController.php, app/Http/HttpKernel.php, phpstan.neon, rector.php, resources/views/_snippets/head.blade.php, routes/web.php, src/Controller/PostImageController.php
- fix paths
- prepare image for posts
=> tv fix images

app/Http/Controller/HomepageController.php, composer.json, composer.lock, patches/canvural-phpstan-blade-rule-src-rules-viewrulehelper-php.patch, phpstan.neon
The original project seems dead.
Trying out fixed branch: https://github.com/alexander-schranz/phpstan-blade-rule
=> [phpstan] Try blade phpstan package

.env.local, .github/workflows/code_analysis.yaml, composer.json, composer.lock, phpunit.xml, tests/AbstractTestCase.php, tests/Repository/PostRepositoryTest.php, tests/Smoking/ControllerSmokeTest.php, tests/bootstrap.php
- use correct kernel
- fixup! use correct kernel
=> Add controller smoke test

composer.json, composer.lock, config/cache.php, config/view.php, resources/css/app.scss, resources/posts/2023/2023-03-08-introducing-punchcard-object-configs-for-laravel.md
- fixup! Add tomasvotruba/laratyped (#1389)
- test
- gram
=> [post] Add punchcard

first-run.sh
=> Fix typo and halt on error (#1392

composer.lock, config/app.php, config/cache.php, config/logging.php, config/session.php
=> Make use of punchard and defaults() :partying_face: 

app/Invoicing/CarReportExtractor.php, app/Repository/CarRepository.php, app/ValueObject/Car.php, app/ValueObject/CarReport.php, app/ValueObject/FuelInvoice.php, app/ValueObject/FuelPurchase.php, resources/database/cars.json, resources/views/helinvoice/invoice.blade.php, resources/views/layout/layout_base.blade.php
- styling
- show cars by id
- cars
=> Collect and integrate feedback

resources/posts/2023/2023-07-25-experiment-how-i-replaced-symfony-di-with-laravel-container-in-ecs.md
Post about https://github.com/easy-coding-standard/easy-coding-standard/pull/105
=> [post] Symfony DI to Laravel container in ECS

resources/posts/2023/2023-08-25-from-symfony-to-laravel-can-laravel-even-compiler-pass.md
=> A few typos and grammar fixes

resources/posts/2020/2020-07-27-how-to-switch-from-yaml-xml-configs-to-php-today-with-migrify.md
=> tv cleanup

app/Entity/Post.php, app/functions.php, resources/posts/2017/2017-12-04-life30-what-will-you-do-when-ai-takes-over-the-world.md, resources/posts/2018/2018-08-27-why-and-how-to-avoid-the-memory-lock.md, resources/posts/2018/2018-10-22-brief-history-of-tools-watching-and-changing-your-php-code.md, resources/posts/2019/2019-05-13-hidden-gems-of-php-packages-psalm-fixing-your-code.md, resources/posts/2019/2019-11-18-how-to-delegate-code-reviews-to-ci.md, resources/posts/2020/2020-01-27-switch-travis-to-github-actions-to-reduce-stress.md, resources/posts/2020/2020-03-09-art-of-letting-go.md, resources/posts/2020/2020-03-30-dont-show-your-privates-to-public.md, resources/posts/2020/2020-08-03-how-give-away-1500-eur--in-1-tweet-and-help-25-people-learn-something-new.md, resources/posts/2021/2021-03-01-best-time-to-switch-gitlab-to-github.md, resources/posts/2021/2021-10-04-7-steps-to-start-with-parallel-run-in-php-cli-app.md, resources/posts/2021/2021-10-11-introducing-up-to-16-times-faster-easy-coding-standard.md, resources/posts/2022/2022-03-07-5-constant-lists-that-give-context-to-your-integers-and-strings.md, resources/posts/2022/2022-04-25-how-to-remove-dead-mock-calls-from-phpunit-tests.md, resources/posts/2022/2022-05-02-how-to-test-symfony-routes-to-make-huge-refactorings-safe.md, resources/posts/2022/2022-06-27-twig-smoke-rendering-fortune-favors-the-bold.md, resources/posts/2022/2022-07-04-can-phpstan-find-dead-public-methods.md, resources/posts/2022/2022-07-25-how-to-develop-sole-package-in-php81-and-downgrade-to-php72.md, resources/posts/2022/2022-11-07-how-to-measure-your-type-coverage.md, resources/posts/2023/2023-01-04-how-can-we-generate-unit-tests-part-1-testability-score.md, resources/posts/2023/2023-02-26-why-I-migrated-this-website-from-symfony-to-laravel.md, resources/posts/2023/2023-07-25-experiment-how-i-replaced-symfony-di-with-laravel-container-in-ecs.md, resources/posts/2023/2023-08-20-easy-and-quick-way-to-measure-lines-of-code-in-php.md, resources/posts/2024/2024-01-27-get-json-output-for-phpunit-10.md, resources/views/post.blade.php
- fix tweet embed
- [post] phpunit json result
- gram
=> [post] add phpunit json result printer

resources/posts/2023/2024-02-03-3-signs-your-project-is-becoming-legacy-mock-rottening.md
=> tv post mock errata

resources/posts/2024/2024-04-17-master-the-change.md
=> tv post change

resources/posts/2024/2024-06-10-2-tricks-to-get-your-symfony-configs-lines-to-minimum.md, resources/posts/2024/2024-06-10-symfony-configs-renovation-care.md, resources/views/homepage.blade.php
- **[post] symfony config rennovation care**
- **gram**
- **fixup! gram**
=> [post] zero symfony configs

composer.json, composer.lock, phpstan.neon, resources/posts/2024/2024-08-27-php-is-the-best-choice-for-long-term-business.md, tests/AbstractTestCase.php
- **[post] php longterm**
- **[post] best php**
- **grams**
=> [post] php best level

resources/views/tools.blade.php, src/Repository/ToolRepository.php, src/ValueObject/Tool.php
=> tv tools 2

resources/views/post.blade.php
open-souce -> open-sou**r**ce in post.blade.php
=> - fixed a typo in post.blade.php

resources/css/app.scss, resources/posts/2025/2025-01-03-why-final-classes-make-rector-and-phpstan-more-powerful.md
- **[post] finalize classes for rector and phpstan**
- **gram**
=> [post] finalize classes for rector and phpstan

resources/posts/2025/2025-01-08-symfony-required-avoid-the-temptation-and-use-it-right.md
- **[post] Add symofny required**
- **gram**
=> [post] Add symofny required

resources/posts/2023/2023-12-30-5-books-i-enyjoed-reading-in-2023.md, resources/posts/2025/2025-01-18-5-books-i-enjoyed-reading-in-2024.md
=> [post] books 2024

resources/views/llms-txt.blade.php, routes/web.php, src/Http/Controllers/LlmsTxtController.php, src/Http/Controllers/PostController.php, src/Http/Controllers/RssController.php
Ref https://github.com/TomasVotruba/tomasvotruba.com/issues/1516
=> tv llm txt

resources/posts/2025/2025-04-17-how-we-maintain-dozens-of-symfony-workflows-with-ease.md, resources/posts/2025/2025-04-17-how-we-maintain-dozens-of-symfony-workflows-with-peace.md, src/Repository/PostRepository.php
- **[post] workflows**
- **fixup! [post] workflows**
- **fixup! fixup! [post] workflows**
- **gram**
=> [post] workflows

resources/views/llms-txt.blade.php, resources/views/post-md.blade.php, routes/web.php, src/Http/Controllers/PostMdController.php
- **[post] md**
- **add md versions**
=> tv llms txt 3
